# Generated by Django 4.2.3 on 2023-10-02 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('type', models.CharField(max_length=50)),
                ('area', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('purpose', models.CharField(choices=[('user_buy', 'User Buy'), ('user_rent', 'User Rent')], max_length=10)),
                ('completion', models.CharField(choices=[('all', 'All'), ('ready', 'Ready'), ('unready', 'Unready'), ('under_construction', 'Under Construction')], max_length=20)),
                ('status', models.CharField(choices=[('booked', 'Booked'), ('available', 'Available')], default='available', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_url', models.CharField(max_length=255)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='all_property.property')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('division', models.CharField(max_length=255)),
                ('district', models.CharField(max_length=255)),
                ('thana_police_station', models.CharField(max_length=255)),
                ('upazila', models.CharField(max_length=255)),
                ('union_ward', models.CharField(max_length=255)),
                ('village', models.CharField(max_length=255)),
                ('property', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='all_property.property')),
            ],
        ),
    ]
