# Generated by Django 4.2.5 on 2023-10-09 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_property', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='img_url',
            field=models.URLField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='completion',
            field=models.CharField(choices=[('all', 'All'), ('ready', 'Ready'), ('incomplete', 'Incomplete'), ('under_construction', 'Under Construction')], max_length=30),
        ),
        migrations.AlterField(
            model_name='property',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='PropertyImage',
        ),
    ]
