# Generated by Django 4.2.5 on 2023-10-02 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_property', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='purpose',
            field=models.CharField(choices=[('sell', 'Sell'), ('rent', 'Rent')], max_length=10),
        ),
    ]
