# Generated by Django 4.2.5 on 2023-10-06 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_property', '0003_rename_type_property_property_type_property_district_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertyimage',
            name='img_url',
        ),
        migrations.AddField(
            model_name='propertyimage',
            name='image',
            field=models.ImageField(default=None, upload_to='uploads/'),
        ),
    ]
