# Generated by Django 4.2.5 on 2023-10-09 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_property', '0003_rename_property_type_property_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='upozila',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
