# Generated by Django 4.2.5 on 2023-10-10 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_property', '0004_alter_property_upozila'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='completion',
            field=models.CharField(default='Ready', max_length=30),
        ),
        migrations.AlterField(
            model_name='property',
            name='district',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='division',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='purpose',
            field=models.CharField(default='Sell', max_length=10),
        ),
        migrations.AlterField(
            model_name='property',
            name='status',
            field=models.CharField(default='Available', max_length=10),
        ),
    ]
