# Generated by Django 4.2.5 on 2023-10-21 15:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('all_property', '0005_alter_property_completion_alter_property_district_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='property',
            name='user',
            field=models.ForeignKey(default=25, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
