# Generated by Django 4.2.5 on 2023-10-22 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_property', '0006_property_likes_property_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='image1',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='image2',
            field=models.URLField(null=True),
        ),
    ]
