# Generated by Django 4.2.5 on 2023-10-22 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('all_property', '0007_property_image1_property_image2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property_Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('property_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='all_property.property')),
            ],
        ),
    ]
