# Generated by Django 4.2.5 on 2023-10-23 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_property', '0008_property_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='image1',
            field=models.URLField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='image2',
            field=models.URLField(max_length=300, null=True),
        ),
    ]
