# Generated by Django 4.2.5 on 2023-10-02 08:51

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0002_alter_testimonial_user'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='testimonial',
            unique_together={('user', 'testimonial_id')},
        ),
    ]
