# Generated by Django 4.2.5 on 2023-10-19 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_promotion_end_date_alter_promotion_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='trans_id',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='payment_status',
            field=models.CharField(default='Pending', max_length=9),
        ),
    ]
