# Generated by Django 4.2.5 on 2023-10-02 09:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0003_alter_testimonial_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('property_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('area', models.IntegerField()),
                ('price', models.IntegerField()),
                ('type', models.CharField(choices=[('Apartment', 'Apartment'), ('Land', 'Land')], max_length=30)),
                ('purpose', models.CharField(blank=True, choices=[('For Sale', 'For Sale'), ('To Rent', 'To Rent')], max_length=30)),
                ('status', models.CharField(blank=True, choices=[('Completed', 'Completed'), ('Under Development', 'Under Development')], max_length=30)),
                ('division', models.CharField(blank=True, max_length=30)),
                ('district', models.CharField(blank=True, max_length=30)),
                ('thana', models.CharField(blank=True, max_length=30)),
                ('upozila', models.CharField(blank=True, max_length=30)),
                ('union_or_ward', models.CharField(blank=True, max_length=30)),
                ('village', models.CharField(blank=True, max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='property_images/')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='dashboard.property')),
            ],
        ),
        migrations.AddField(
            model_name='property',
            name='property_images',
            field=models.ManyToManyField(related_name='properties', to='dashboard.propertyimage'),
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('promotion_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.property')),
            ],
        ),
        migrations.CreateModel(
            name='Favourites',
            fields=[
                ('favourite_id', models.AutoField(primary_key=True, serialize=False)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.property')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('booking_id', models.AutoField(primary_key=True, serialize=False)),
                ('booking_date', models.DateTimeField()),
                ('total_amount', models.IntegerField()),
                ('payment_status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed')], default='Pending', max_length=9)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.property')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
