# Generated by Django 4.2.5 on 2023-10-02 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_property_propertyimage_property_property_images_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertyimage',
            name='property',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='property',
        ),
        migrations.RemoveField(
            model_name='favourites',
            name='property',
        ),
        migrations.RemoveField(
            model_name='promotion',
            name='property',
        ),
        migrations.DeleteModel(
            name='Property',
        ),
        migrations.DeleteModel(
            name='PropertyImage',
        ),
    ]
