# Generated by Django 4.2.5 on 2023-10-19 17:05

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('all_property', '0005_alter_property_completion_alter_property_district_and_more'),
        ('dashboard', '0005_alter_booking_payment_status'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favourites',
            unique_together={('user', 'property')},
        ),
    ]
