# Generated by Django 4.2.5 on 2023-10-02 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('all_property', '0002_alter_property_purpose'),
        ('dashboard', '0005_remove_propertyimage_property_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='property',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, to='all_property.property'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='favourites',
            name='property',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='all_property.property'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='promotion',
            name='property',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='all_property.property'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='promotion',
            name='end_date',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='start_date',
            field=models.DateTimeField(blank=True),
        ),
    ]
